### ISSUE TITLE
Proc missing 3rd argument om_range

### ISSUE THREAD

**Issue by DameonOwen** [ARF-SS13/ARFS-5#115]
get_map_levels should have 3 arguments: srcz, longrange, and om_range. Our map does not have om_range. Code should be added to provide this argument. Example can be found at second link.

https://github.com/ARF-SS13/ARFS-5/blob/8cc90431cd5609b8a47d6bd4a6c5dd526d5bb3be/maps/Arfs/arfs_defines.dm#L76
https://github.com/ARF-SS13/ARFS-5/blob/c4b176a1da0f77670ca3391e979beed42edd7708/maps/~map_system/maps.dm#L205

**Comment by DameonOwen** [comment]
This generated 50,000+ debug log entries in 3.5 hours.

**Comment by TalkingCactus** [comment]
Not seeing this on our last map https://github.com/ARF-SS13/ARFS-5/blob/master/maps/yw/cryogaia_defines.dm#L229

**Comment by TalkingCactus** [comment]
Just because it's not defined in our map's version, doesn't mean it goes away, too

**Comment by TalkingCactus** [comment]
it'll just use -1 which should work fine?
